# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-pkg-cache
      - run:
          name: unit tests
          command: go test -v ./...
      - save_cache:
          key: v1-pkg-cache
          paths:
            - "/go/pkg"
      - setup_remote_docker
      - run:
          name: build docker image
          command: docker build -t yaien/cloth-store-api:dev .
      - run:
          name: push docker image
          command: |
              docker login --username-_ --password=${HEROKU_TOKEN} registry.heroku.com
              docker tag yaien/cloth-store-api:dev registry.heroku.com/${HEROKU_APP}/web
              docker push registry.heroku.com/${HEROKU_APP}/web 