# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2

jobs:
  test:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-pkg-cache
      - run: 
          name: install dependencies
          command: go mod download 
      - run:
          name: Run Unit tests
          command: go test -v ./...
      - save_cache:
          key: v1-pkg-cache
          paths:
            - "/go/pkg"
      
  deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: install heroku
          command: curl https://cli-assets.heroku.com/install.sh | sh
      - run: 
          name: login heroku
          command: heroku container:login
      - run:
          name: push container
          command: heroku container:push web --app ${HEROKU_APP}
      - run:
          name: release container 
          command: heroku container:release web --app ${HEROKU_APP}

workflows:
  version: 2
  workflow: 
    jobs:
      - test
      - deploy

          