# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-pkg-cache
      - run: 
          name: unit tests
          command: go test -v ./...
      - save_cache:
          key: v1-pkg-cache
          paths:
            - "/go/pkg"
  deploy-dev:
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: 
        name: building docker image
        command: docker build -t yaien/cloth-store-api:dev .      

workflows:
  version: 2
  dev:
    jobs:
      - build
      - deploy-dev:
        requires: build