name: Build
on:
  pull_request:
    branches:
      - master
      - development
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Run unit tests
        run: go test ./...
      - name: Build
        run: go build ./cmd/store
